### ISSUE TITLE
How to deploy results?

### ISSUE THREAD

**Issue by YuetongBi** [FranciscoRiano/team9_airbnb_amsterdam_analysis#2]

**Comment by janvanderdoe** [comment]
You mean the results of our regression etc.?

**Comment by YuetongBi** [comment]
I mean the way to show results of regression analysis etc., for example, dashboard or PDF. 
We can just keep this question for later

**Comment by YuetongBi** [comment]
> You mean the results of our regression etc.?
I mean the way to show results of regression analysis etc., for example, dashboard or PDF.
We can just keep this question for later

**Comment by janvanderdoe** [comment]
How about a markdown file? That's a quick and easy way to show results
