### ISSUE TITLE
Split analysis file

### ISSUE THREAD

**Issue by pommeverhagen** [FranciscoRiano/team9_airbnb_amsterdam_analysis#8]

**Comment by kammaj** [comment]
Hi, Jan could you please make the outputs (plots/tables) in separate pdfs? This way we will be able to use it in our final report because I did not figure out how to do it with one multipage pdf. Thanks a lot and let me know if you need help

**Comment by janvanderdoe** [comment]
I thought the idea was to include the code itself in the Rmd. I don't think you have to include every graph, just the most important ones

**Comment by kammaj** [comment]
Yes, I know but I was having some troubles (I guess my pc was not handling it), so I made separate pics of the outputs and used in to the report. Feel free to change it though :)
